export const hashtagMockData = [
  { name: "music", count: 18.2 },
  { name: "movies", count: 15.7 },
  { name: "food", count: 19.4 },
  { name: "gaming", count: 12.8 },
  { name: "photography", count: 8.3 },
  { name: "travel", count: 16.5 },
  { name: "cooking", count: 11.2 },
  { name: "reading", count: 14.9 },
  { name: "fitness", count: 17.1 },
  { name: "hiking", count: 9.4 },
  { name: "art", count: 13.6 },
  { name: "dancing", count: 7.8 },
  { name: "gardening", count: 5.2 },
  { name: "tech", count: 18.9 },
  { name: "science", count: 10.5 },
  { name: "history", count: 6.7 },
  { name: "nature", count: 14.2 },
  { name: "yoga", count: 12.1 },
  { name: "swimming", count: 8.9 },
  { name: "cycling", count: 11.5 },
  { name: "writing", count: 9.8 },
  { name: "podcasts", count: 13.4 },
  { name: "fashion", count: 15.2 },
  { name: "interiordesign", count: 7.4 },
  { name: "diy", count: 6.9 },
  { name: "sustainability", count: 10.8 },
  { name: "meditation", count: 11.9 },
  { name: "skating", count: 4.6 },
  { name: "astronomy", count: 3.8 },
  { name: "languages", count: 12.5 },
  { name: "volunteering", count: 8.7 },
  { name: "baking", count: 13.9 },
  { name: "animation", count: 9.2 },
  { name: "chess", count: 5.5 },
  { name: "coffee", count: 19.8 },
  { name: "dancing", count: 7.8 },
  { name: "gardening", count: 5.2 },
  { name: "tech", count: 18.9 },
  { name: "science", count: 10.5 },
  { name: "history", count: 6.7 },
  { name: "nature", count: 14.2 },
  { name: "yoga", count: 12.1 },
  { name: "swimming", count: 8.9 },
  { name: "cycling", count: 11.5 },
  { name: "writing", count: 9.8 },
];

export const feedMockData = [
  {
    name: "Alex Smith",
    content: "Just finished a great workout! Feeling energized.",
    likes: 24,
    comments: 8,
    timestamp: "5m",
    personality: "INTJ",
    zodiac: "Leo",
    points: 85,
  },
  {
    name: "Jordan Lee",
    content: "Anyone have recommendations for a good sci-fi book?",
    likes: 12,
    comments: 15,
    timestamp: "12m",
    personality: "ESFP",
    zodiac: "Sagittarius",
    points: 42,
  },
  {
    name: "Taylor Reed",
    content: "The sunset today was absolutely breathtaking.",
    likes: 56,
    comments: 3,
    timestamp: "45m",
    personality: "INFP",
    zodiac: "Pisces",
    points: 77,
  },
  {
    name: "Casey Morgan",
    content: "Can't wait for the weekend trip to the mountains!",
    likes: 31,
    comments: 7,
    timestamp: "1h",
    personality: "ENFJ",
    zodiac: "Aries",
    points: 63,
  },
  {
    name: "Riley Davis",
    content: "Trying out a new pasta recipe tonight. Wish me luck!",
    likes: 18,
    comments: 4,
    timestamp: "2h",
    personality: "ISTJ",
    zodiac: "Taurus",
    points: 29,
  },
  {
    name: "Morgan Blair",
    content: "Just saw the most amazing street performance.",
    likes: 42,
    comments: 9,
    timestamp: "3h",
    personality: "ENTP",
    zodiac: "Gemini",
    points: 58,
  },
  {
    name: "Parker Quinn",
    content: "What's the best way to learn a new language quickly?",
    likes: 9,
    comments: 21,
    timestamp: "5h",
    personality: "ISFJ",
    zodiac: "Cancer",
    points: 34,
  },
  {
    name: "Skyler Finn",
    content: "Finally finished my latest painting project.",
    likes: 72,
    comments: 12,
    timestamp: "6h",
    personality: "INFJ",
    zodiac: "Scorpio",
    points: 91,
  },
  {
    name: "Jamie Lane",
    content: "Coffee and a good book - the perfect morning.",
    likes: 38,
    comments: 2,
    timestamp: "8h",
    personality: "ESFJ",
    zodiac: "Libra",
    points: 47,
  },
  {
    name: "Dakota Sky",
    content: "Does anyone else find coding so relaxing sometimes?",
    likes: 27,
    comments: 14,
    timestamp: "10h",
    personality: "ISTP",
    zodiac: "Virgo",
    points: 52,
  },
  {
    name: "Peyton Cole",
    content: "Late night study sessions are the best.",
    likes: 15,
    comments: 6,
    timestamp: "12h",
    personality: "ENFP",
    zodiac: "Aquarius",
    points: 38,
  },
  {
    name: "Reese West",
    content: "The ocean breeze is so rejuvenating.",
    likes: 49,
    comments: 5,
    timestamp: "14h",
    personality: "ISFP",
    zodiac: "Capricorn",
    points: 66,
  },
  {
    name: "Quinn Hayes",
    content: "Learning to play the guitar is harder than I thought!",
    likes: 22,
    comments: 18,
    timestamp: "16h",
    personality: "ESTJ",
    zodiac: "Aries",
    points: 25,
  },
  {
    name: "Emerson Grey",
    content: "A quick weekend getaway is all I needed.",
    likes: 64,
    comments: 11,
    timestamp: "18h",
    personality: "INTP",
    zodiac: "Sagittarius",
    points: 73,
  },
  {
    name: "Avery Frost",
    content: "Fresh flowers make everything better.",
    likes: 33,
    comments: 4,
    timestamp: "20h",
    personality: "ENTJ",
    zodiac: "Leo",
    points: 81,
  },
  {
    name: "Logan Pine",
    content: "Watching my favorite movie for the 10th time.",
    likes: 19,
    comments: 7,
    timestamp: "22h",
    personality: "INTJ",
    zodiac: "Taurus",
    points: 15,
  },
  {
    name: "Robin Wells",
    content: "Nature walks are the best therapy.",
    likes: 51,
    comments: 8,
    timestamp: "1d",
    personality: "ESFP",
    zodiac: "Cancer",
    points: 94,
  },
  {
    name: "Blake Stone",
    content: "Just discovered a new favorite cafe.",
    likes: 36,
    comments: 13,
    timestamp: "2d",
    personality: "INFP",
    zodiac: "Virgo",
    points: 44,
  },
  {
    name: "Drew Banks",
    content: "Exploring the city streets on a sunny day.",
    likes: 47,
    comments: 6,
    timestamp: "3d",
    personality: "ENFJ",
    zodiac: "Libra",
    points: 55,
  },
  {
    name: "Sloan Reed",
    content: "Grateful for the small things in life.",
    likes: 82,
    comments: 15,
    timestamp: "4d",
    personality: "ISTJ",
    zodiac: "Scorpio",
    points: 98,
  },
  {
    name: "Hayden Bell",
    content: "Can't wait for the upcoming concert!",
    likes: 29,
    comments: 10,
    timestamp: "5d",
    personality: "ENTP",
    zodiac: "Pisces",
    points: 31,
  },
  {
    name: "Phoenix Ash",
    content: "New music alert! Check out my latest playlist.",
    likes: 14,
    comments: 5,
    timestamp: "6d",
    personality: "ISFJ",
    zodiac: "Gemini",
    points: 12,
  },
  {
    name: "River Hart",
    content: "The stars are so clear tonight.",
    likes: 58,
    comments: 9,
    timestamp: "1w",
    personality: "INFJ",
    zodiac: "Aquarius",
    points: 88,
  },
  {
    name: "Sage Moss",
    content: "Feeling thankful for my amazing friends.",
    likes: 41,
    comments: 12,
    timestamp: "2w",
    personality: "ESFJ",
    zodiac: "Taurus",
    points: 60,
  },
  {
    name: "Jesse Dale",
    content: "Sunday brunch is my favorite tradition.",
    likes: 26,
    comments: 3,
    timestamp: "3w",
    personality: "ISTP",
    zodiac: "Leo",
    points: 39,
  },
  {
    name: "Ocean Blue",
    content: "Finally conquered my fear of heights!",
    likes: 95,
    comments: 24,
    timestamp: "1mo",
    personality: "ENFP",
    zodiac: "Aries",
    points: 99,
  },
  {
    name: "Winter Snow",
    content: "Cozy vibes and warm blankets.",
    likes: 34,
    comments: 6,
    timestamp: "2mo",
    personality: "ISFP",
    zodiac: "Capricorn",
    points: 22,
  },
  {
    name: "Ash Woods",
    content: "The first snow of the season is here.",
    likes: 67,
    comments: 18,
    timestamp: "2mo",
    personality: "ESTJ",
    zodiac: "Sagittarius",
    points: 79,
  },
  {
    name: "Indigo Rain",
    content: "Dancing in the rain is so much fun!",
    likes: 43,
    comments: 11,
    timestamp: "3mo",
    personality: "INTP",
    zodiac: "Aquarius",
    points: 54,
  },
  {
    name: "Marlowe Vane",
    content: "Dreaming of my next big adventure.",
    likes: 21,
    comments: 7,
    timestamp: "4mo",
    personality: "ENTJ",
    zodiac: "Virgo",
    points: 41,
  },
];
